#!/usr/bin/env python3
"""
Script to convert markdown files to structured JSON using LLM.
Reads the mapping file generated by html_to_markdown_service.py and converts
the markdown files to structured JSON format.
"""

import sys
import argparse
import json
from pathlib import Path

# Add the src directory to the path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.json.html_to_json_service import HtmlToJsonService
from src.llm import LLMClient


def setup_argparse():
    """Setup command line argument parsing."""
    parser = argparse.ArgumentParser(
        description="Convert markdown files to structured JSON using LLM",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Convert using default markdown mapping file
  python convert_markdown_to_json.py

  # Specify custom input directory and mapping file
  python convert_markdown_to_json.py -i /path/to/html/output -m sections_questions_mapping_markdown.json

  # Specify custom output directory
  python convert_markdown_to_json.py -o /path/to/json/output

  # Use specific LLM providers
  python convert_markdown_to_json.py --providers anthropic openai

  # Enable verbose output
  python convert_markdown_to_json.py -v
        """
    )
    
    parser.add_argument(
        "-i", "--input-dir",
        type=Path,
        help="Input directory containing markdown files and mapping (default: current directory)"
    )
    
    parser.add_argument(
        "-m", "--mapping-file",
        type=str,
        default="sections_questions_mapping_markdown.json",
        help="Mapping file name (default: sections_questions_mapping_markdown.json)"
    )
    
    parser.add_argument(
        "-o", "--output-dir",
        type=Path,
        help="Output directory for JSON files (default: input_dir/json_from_markdown)"
    )
    
    parser.add_argument(
        "--providers",
        nargs="+",
        choices=["anthropic", "openai"],
        default=["anthropic", "openai"],
        help="LLM providers to use in order of preference (default: anthropic openai)"
    )
    
    parser.add_argument(
        "--retry-attempts",
        type=int,
        default=3,
        help="Number of retry attempts for LLM calls (default: 3)"
    )
    
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="Temperature for LLM calls (default: 0.0 for consistent results)"
    )
    
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose output"
    )
    
    return parser


def validate_inputs(args):
    """Validate input arguments and paths."""
    # Determine input directory
    if args.input_dir:
        input_dir = args.input_dir
    else:
        input_dir = Path.cwd()
    
    if not input_dir.exists():
        raise ValueError(f"Input directory does not exist: {input_dir}")
    
    # Find mapping file
    mapping_file = input_dir / args.mapping_file
    if not mapping_file.exists():
        raise ValueError(f"Mapping file not found: {mapping_file}")
    
    # Check for markdown directories
    md_sections_dir = input_dir / "sections_md"
    md_questions_dir = input_dir / "questions_md"
    
    if not md_sections_dir.exists():
        raise ValueError(f"Markdown sections directory not found: {md_sections_dir}")
    
    if not md_questions_dir.exists():
        raise ValueError(f"Markdown questions directory not found: {md_questions_dir}")
    
    # Determine output directory
    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = input_dir / "json_from_markdown"
    
    return input_dir, mapping_file, output_dir


def print_mapping_info(mapping, verbose=False):
    """Print information about the mapping file."""
    metadata = mapping.get("metadata", {})
    
    print(f"Source HTML file: {metadata.get('html_source_file', 'Unknown')}")
    print(f"Total sections: {metadata.get('total_sections', 0)}")
    print(f"Total questions: {metadata.get('total_questions', 0)}")
    
    if verbose:
        conversion_stats = metadata.get("conversion_stats", {})
        if conversion_stats:
            print(f"Markdown conversion stats:")
            print(f"  - Sections converted: {conversion_stats.get('sections_converted', 0)}")
            print(f"  - Questions converted: {conversion_stats.get('questions_converted', 0)}")
            print(f"  - Errors: {len(conversion_stats.get('errors', []))}")
    
    print()


def main():
    """Main script execution."""
    parser = setup_argparse()
    args = parser.parse_args()
    
    try:
        # Validate inputs
        input_dir, mapping_file, output_dir = validate_inputs(args)
        
        if args.verbose:
            print(f"Input directory: {input_dir}")
            print(f"Mapping file: {mapping_file}")
            print(f"Output directory: {output_dir}")
            print(f"LLM providers: {args.providers}")
            print()
        
        # Load and display mapping information
        with open(mapping_file, 'r', encoding='utf-8') as f:
            mapping = json.load(f)
        
        print("=== Markdown to JSON Conversion ===")
        print_mapping_info(mapping, verbose=args.verbose)
        
        # Initialize LLM client
        if args.verbose:
            print("Initializing LLM client...")
        
        llm_client = LLMClient(
            providers=args.providers,
            retry_attempts=args.retry_attempts,
            retry_delay=1.0,
            retry_backoff=2.0
        )
        
        # Initialize conversion service
        service = HtmlToJsonService(
            llm_client=llm_client,
            verbose=args.verbose
        )
        
        # Perform conversion
        print("Starting conversion to JSON...")
        print("This may take a while depending on the number of files and LLM response times.")
        print()
        
        results = service.convert_from_mapping(
            mapping_file=mapping_file,
            source_type="markdown",
            output_dir=output_dir
        )
        
        # Print detailed results
        print("\n=== Conversion Results ===")
        stats = results['conversion_stats']
        
        print(f"Sections processed: {stats['sections_processed']}")
        print(f"Sections successful: {stats['sections_success']}")
        print(f"Elements processed: {stats['elements_processed']}")
        print(f"Elements successful: {stats['elements_success']}")
        
        tokens_used = stats['total_tokens_used']
        print(f"Total tokens used: {tokens_used['input']} input, {tokens_used['output']} output")
        
        if stats['errors']:
            print(f"\nErrors ({len(stats['errors'])}):")
            for error in stats['errors'][:10]:  # Show first 10 errors
                print(f"  - {error}")
            if len(stats['errors']) > 10:
                print(f"  ... and {len(stats['errors']) - 10} more errors")
        
        # Success rate
        section_success_rate = (stats['sections_success'] / stats['sections_processed'] * 100) if stats['sections_processed'] > 0 else 0
        element_success_rate = (stats['elements_success'] / stats['elements_processed'] * 100) if stats['elements_processed'] > 0 else 0
        
        print(f"\nSuccess rates:")
        print(f"  - Sections: {section_success_rate:.1f}%")
        print(f"  - Elements: {element_success_rate:.1f}%")
        
        # Output locations
        print(f"\nOutput files saved to: {output_dir}")
        report_file = output_dir / "conversion_report.json"
        print(f"Detailed report: {report_file}")
        
        # Return appropriate exit code
        if stats['errors']:
            print(f"\n⚠ Conversion completed with {len(stats['errors'])} errors")
            return 1
        else:
            print(f"\n✓ Conversion completed successfully")
            return 0
            
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
